pipeline {
    agent any

    tools {
        maven "maven-3.9"
    }

    environment {
        SETTINGS = credentials('maven-settings')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh "mvn -s $SETTINGS clean install"
            }
        }

        stage('Publish to Nexus') {
            when {
                branch 'main'
            }
            steps {
                sh "mvn -s $SETTINGS deploy"
            }
        }

        stage('Deploy to Test') {
            when {
                branch 'main'
            }
            steps {
                sh """
                    ansible-playbook -i ansible/inventory ansible/deploy-test.yml \
                        --extra-vars "artifact=target/*.war"
                """
            }
        }

        stage('Approve Prod Deployment') {
            when {
                branch 'main'
            }
            steps {
                input message: "Czy wdrożyć na PROD?"
            }
        }

        stage('Deploy to Prod') {
            when {
                branch 'main'
            }
            steps {
                sh """
                    ansible-playbook -i ansible/inventory ansible/deploy-prod.yml \
                        --extra-vars "artifact=target/*.war"
                """
            }
        }
    }
}
