pipeline {
    agent any

    tools {
        maven "maven-3.9"
    }

    environment {
        SETTINGS = credentials('maven-settings')
	SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh "mvn -s $SETTINGS -f app/pom.xml clean install"
            }
        }

	stage('SonarQube Analysis') {
    		when { branch 'main' }
    		steps {
        		withSonarQubeEnv('MySonar') {
            		sh """
                		mvn -s $SETTINGS -f app/pom.xml clean verify sonar:sonar \
                  		-Dsonar.projectKey=myapp \
                  		-Dsonar.host.url=http://sonarqube1:9000 \
                  		-Dsonar.login=${SONAR_TOKEN}
            		"""
        		}
    		}
	}

        stage('Publish to Nexus') {
            when { branch 'main' }
            steps {
                sh "mvn -s $SETTINGS -f app/pom.xml deploy"
            }
        }

        stage('Deploy to Test') {
            when { branch 'main' }
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'ssh-devops-pass',
                        usernameVariable: 'SSH_USER',
                        passwordVariable: 'SSH_PASS'
                    )
                ]) {
                    sh """
                        ansible-playbook -i cicd/ansible/inventory cicd/ansible/deploy-test.yml \
                            --extra-vars "ansible_user=${SSH_USER}" \
                            --extra-vars "ansible_password=${SSH_PASS}" \
			    --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
                            --extra-vars "artifact=${env.WORKSPACE}/app/target/myapp-1.0.0.war"
                    """
                }
            }
        }

        stage('Approve Prod Deployment') {
            when { branch 'main' }
            steps {
                input message: "Do you want to deploy on PROD?"
            }
        }

        stage('Deploy to Prod') {
            when { branch 'main' }
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'ssh-devops-pass',
                        usernameVariable: 'SSH_USER',
                        passwordVariable: 'SSH_PASS'
                    )
                ]) {
                    sh """
                        ansible-playbook -i cicd/ansible/inventory cicd/ansible/deploy-prod.yml \
                            --extra-vars "ansible_user=${SSH_USER}" \
                            --extra-vars "ansible_password=${SSH_PASS}" \
			    --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
                            --extra-vars "artifact=${env.WORKSPACE}/app/target/myapp-1.0.0.war"
                    """
                }
            }
        }
    }
}
