pipeline {
    agent any

    tools {
        maven "maven-3.9"
    }

    environment {
        SETTINGS = credentials('maven-settings')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh "mvn -s $SETTINGS -f app/pom.xml clean install"
            }
        }

        stage('Publish to Nexus') {
            when {
                branch 'main'
            }
            steps {
                sh "mvn -s $SETTINGS -f app/pom.xml deploy"
            }
        }

        stage('Deploy to Test') {
            when {
                branch 'main'
            }
            steps {
                sh """
		    
		    echo "[CI/CD] Deploy to TEST"

            	    cp ${env.WORKSPACE}/app/target/myapp-1.0.0.war /tmp/app.war

            	    echo "[CI/CD] Copying WAR into test1 using docker exec + cat"
            	    docker exec test1 sh -c 'cat > /opt/tomcat/webapps/app.war' < /tmp/app.war

            	    echo "[CI/CD] Restarting Test container"
            	    docker restart test1

                """
            }
        }

        stage('Approve Prod Deployment') {
            when {
                branch 'main'
            }
            steps {
                input message: "Czy wdrożyć na PROD?"
            }
        }

        stage('Deploy to Prod') {
            when {
                branch 'main'
            }
            steps {
                sh """
		    echo "[CI/CD] Deploy to TEST"

                    cp ${env.WORKSPACE}/app/target/myapp-1.0.0.war /tmp/app.war

                    echo "[CI/CD] Copying WAR into test1 using docker exec + cat"
                    docker exec test1 sh -c 'cat > /opt/tomcat/webapps/app.war' < /tmp/app.war

                    echo "[CI/CD] Restarting Test container"
                    docker restart prod1
                """
            }
        }
    }
}
