- hosts: prod

  tasks:
    - name: Copy app to prod tomcat
      copy:
        src: "{{ artifact }}"
        dest: /opt/tomcat/webapps/app.war
        mode: '0644'

    - name: Restart Prod container
      shell: docker restart prod
